[[plugins]]
repository = 'sjl/gundo.vim'
commands = 'GundoToggle'

[[plugins]]
repository = 'Shougo/neocomplete.vim'
depends = 'Shougo/context_filetype.vim'
insert = 1

[[plugins]]
repository = 'thinca/vim-quickrun'
mappings = '<Plug>'

[[plugins]]
repository = 'Shougo/unite.vim'
depends = 'Shougo/neomru.vim'

  [plugins.commands]
  name = 'Unite'
  complete = 'customlist,unite#complete_source'

[[plugins]]
repository = 'Shougo/unite-help'

[[plugins]]
repository = 'Shougo/vimshell.vim'
mappings = '<Plug>'

  [plugins.commands]
  name = 'VimShell'
  complete = 'customlist,vimshell#complete'
